In [0]:
from sklearn import svm
import numpy as np
from sklearn.metrics import accuracy_score,confusion_matrix

In [19]:
for kernel in ('linear', 'poly', 'rbf','sigmoid'):
    print('Fitting Model With '+kernel+' Kernel')
    model =svm.SVC(kernel=kernel)
    print('Model Fitted')

    X = np.load('images.npy')
    X =np.reshape(X,[900,1200])
    Y = np.load('labels.npy')
    model.fit(X,Y)
    x_test = np.load('test_images.npy')
    y_test = np.load('test_labels.npy')
    y_t=model.predict(x_test)
    print(accuracy_score(y_test,y_t))
    print(confusion_matrix(y_test,y_t))
    print('------------------------------------')

Fitting Model With linear Kernel
Model Fitted


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.23
[[10  0  0  0  0  0  0  0  0  0]
 [ 0  2  1  0  0  2  1  1  1  2]
 [ 0  0  2  0  0  4  0  4  0  0]
 [ 0  0  2  1  2  1  1  1  2  0]
 [ 0  4  1  4  0  1  0  0  0  0]
 [ 0  1  0  0  1  3  0  0  2  3]
 [ 0  3  1  1  1  1  0  2  0  1]
 [ 0  1  1  0  1  4  0  0  3  0]
 [ 0  2  0  0  0  1  0  2  2  3]
 [ 0  1  0  0  1  4  0  0  1  3]]
------------------------------------
Fitting Model With poly Kernel
Model Fitted


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.1
[[10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [ 7  0  0  0  0  1  0  0  0  2]
 [ 4  0  0  0  0  2  0  1  0  3]
 [10  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  3  0  1  0  4]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]]
------------------------------------
Fitting Model With rbf Kernel
Model Fitted


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.51
[[10  0  0  0  0  0  0  0  0  0]
 [ 0  7  0  0  0  0  0  3  0  0]
 [ 0  0  2  0  0  2  0  6  0  0]
 [ 0  0  0 10  0  0  0  0  0  0]
 [ 0  0  0  1  6  0  3  0  0  0]
 [ 0  0  1  0  0  9  0  0  0  0]
 [ 0  0  0  2  6  0  2  0  0  0]
 [ 0  0  3  0  0  2  0  0  0  5]
 [ 0  0  0  0  0  8  0  0  1  1]
 [ 0  0  1  0  0  5  0  0  0  4]]
------------------------------------
Fitting Model With sigmoid Kernel
Model Fitted


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.27
[[10  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  2  0  5  1  1]
 [ 0  0  1  0  0  4  0  5  0  0]
 [ 0  0  1  1  0  1  0  2  3  2]
 [ 1  0  4  0  1  2  0  1  0  1]
 [ 0  0  1  0  0  9  0  0  0  0]
 [ 0  0  1  1  0  0  0  4  1  3]
 [ 0  0  3  0  0  4  0  0  0  3]
 [ 0  0  0  0  0  9  0  0  1  0]
 [ 0  0  1  0  0  4  0  1  0  4]]
------------------------------------


In [0]:
for i in range(1,20,1):
    print('Fitting Model With '+'poly'+' Kernel and Degree '+str(i))
    model =svm.SVC(kernel='poly',degree=i)
    print('Model Fitted')
    X = np.load('images.npy')
    X =np.reshape(X,[900,1200])
    Y = np.load('labels.npy')
    model.fit(X,Y)
    x_test = np.load('test_images.npy')
    y_test = np.load('test_labels.npy')
    y_t=model.predict(x_test)
    print(accuracy_score(y_test,y_t))
    print(confusion_matrix(y_test,y_t))
    print('------------------------------------')

Fitting Model With poly Kernel and Degree 1
Model Fitted


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.27
[[10  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  2  0  5  1  1]
 [ 0  0  1  0  0  4  0  5  0  0]
 [ 0  0  1  1  0  1  0  2  3  2]
 [ 1  0  4  0  1  2  0  1  0  1]
 [ 0  0  1  0  0  9  0  0  0  0]
 [ 0  0  1  1  0  0  0  4  1  3]
 [ 0  0  3  0  0  4  0  0  0  3]
 [ 0  0  0  0  0  9  0  0  1  0]
 [ 0  0  1  0  0  4  0  1  0  4]]
------------------------------------
Fitting Model With poly Kernel and Degree 2
Model Fitted


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.36
[[10  0  0  0  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  0  0]
 [ 6  0  2  0  0  2  0  0  0  0]
 [ 0  0  1  4  0  0  0  0  1  4]
 [ 0  0  0  0  0  0  0  6  0  4]
 [ 6  0  0  0  0  4  0  0  0  0]
 [ 0  0  4  0  0  0  0  6  0  0]
 [ 6  0  0  0  0  2  0  2  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [ 6  0  0  0  0  0  0  0  0  4]]
------------------------------------
Fitting Model With poly Kernel and Degree 3
Model Fitted


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.1
[[10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [ 7  0  0  0  0  1  0  0  0  2]
 [ 4  0  0  0  0  2  0  1  0  3]
 [10  0  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  3  0  1  0  4]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]]
------------------------------------
Fitting Model With poly Kernel and Degree 4
Model Fitted


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.1
[[10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [ 5  0  0  0  0  0  0  0  0  5]
 [ 0  0  0  0  0  0  0  3  0  7]
 [10  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  1  0  2  0  5]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]]
------------------------------------
Fitting Model With poly Kernel and Degree 5
Model Fitted


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.1
[[10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [ 4  0  0  0  0  2  0  1  0  3]
 [10  0  0  0  0  0  0  0  0  0]
 [ 8  0  0  0  0  1  0  0  0  1]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]]
------------------------------------
Fitting Model With poly Kernel and Degree 6
Model Fitted


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.1
[[10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  1  0  9]
 [10  0  0  0  0  0  0  0  0  0]
 [ 0  0  1  0  0  4  0  0  0  5]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]]
------------------------------------
Fitting Model With poly Kernel and Degree 7
Model Fitted


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.1
[[10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [ 6  0  0  0  0  0  0  1  0  3]
 [10  0  0  0  0  0  0  0  0  0]
 [ 9  0  0  0  0  0  0  0  0  1]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]]
------------------------------------
Fitting Model With poly Kernel and Degree 8
Model Fitted


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.1
[[10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 10]
 [10  0  0  0  0  0  0  0  0  0]
 [ 3  0  1  0  0  3  0  0  0  3]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]]
------------------------------------
Fitting Model With poly Kernel and Degree 9
Model Fitted


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.19
[[10  0  0  0  0  0  0  0  0  0]
 [ 3  0  0  0  0  5  0  0  0  2]
 [ 2  0  0  0  0  6  0  0  0  2]
 [ 0  0  0  0  0  2  0  0  0  8]
 [ 2  0  0  0  0  4  0  0  0  4]
 [ 2  0  0  0  0  5  0  0  0  3]
 [ 1  0  0  0  0  5  0  0  0  4]
 [ 1  0  0  0  0  4  0  0  0  5]
 [ 1  0  0  0  0  3  0  0  0  6]
 [ 5  0  0  0  0  1  0  0  0  4]]
------------------------------------
Fitting Model With poly Kernel and Degree 10
Model Fitted


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.3
[[10  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  5]
 [ 0  0  0  0  0  5  0  0  0  5]
 [ 0  0  0  0  0  0  0  0  0 10]
 [ 0  0  0  0  0  0  0  0  0 10]
 [ 0  0  0  0  0 10  0  0  0  0]
 [ 0  0  1  0  0  2  0  0  0  7]
 [ 0  0  0  0  0  1  0  0  0  9]
 [ 0  0  0  0  0  0  0  0  0 10]
 [ 0  0  0  0  0  0  0  0  0 10]]
------------------------------------
Fitting Model With poly Kernel and Degree 11
Model Fitted


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.22
[[10  0  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  3  0  5  0  1]
 [ 0  0  0  0  0  0  0  9  0  1]
 [ 0  0  0  0  0  0  0  7  0  3]
 [ 2  0  0  0  0  1  0  3  0  4]
 [ 1  0  0  0  0  6  0  1  0  2]
 [ 1  0  0  0  0  2  0  5  0  2]
 [ 2  0  0  0  0  3  0  2  0  3]
 [ 1  0  0  0  0  1  0  6  0  2]
 [ 2  0  0  0  0  0  0  4  0  4]]
------------------------------------
Fitting Model With poly Kernel and Degree 12
Model Fitted


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.56
[[10  0  0  0  0  0  0  0  0  0]
 [ 0  0  6  0  0  0  0  2  2  0]
 [ 0  0 10  0  0  0  0  0  0  0]
 [ 0  0  4  0  0  0  0  0  6  0]
 [ 0  0  4  0  0  0  0  6  0  0]
 [ 0  0  1  0  0  8  0  1  0  0]
 [ 0  0  9  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0 10  0  0]
 [ 0  0  0  0  0  0  0  1  9  0]
 [ 0  0  0  0  0  0  0  1  0  9]]
------------------------------------
Fitting Model With poly Kernel and Degree 13
Model Fitted


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.34
[[10  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  1  0  3  4  0]
 [ 0  0  9  0  0  0  0  0  1  0]
 [ 0  0  5  0  0  0  0  1  3  1]
 [ 0  0  3  0  0  0  0  3  1  3]
 [ 0  0  3  0  0  4  0  0  3  0]
 [ 0  0  3  0  0  1  0  2  4  0]
 [ 0  0  5  0  0  0  0  2  3  0]
 [ 0  0  1  0  0  0  0  3  6  0]
 [ 0  0  3  0  0  0  0  2  2  3]]
------------------------------------
Fitting Model With poly Kernel and Degree 14
Model Fitted


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.56
[[10  0  0  0  0  0  0  0  0  0]
 [ 0  0  6  0  0  0  0  2  2  0]
 [ 0  0 10  0  0  0  0  0  0  0]
 [ 0  0  4  0  0  0  0  0  6  0]
 [ 0  0  4  0  0  0  0  6  0  0]
 [ 0  0  1  0  0  8  0  1  0  0]
 [ 0  0  9  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0 10  0  0]
 [ 0  0  0  0  0  0  0  1  9  0]
 [ 0  0  0  0  0  0  0  1  0  9]]
------------------------------------
Fitting Model With poly Kernel and Degree 15
Model Fitted


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.34
[[10  0  0  0  0  0  0  0  0  0]
 [ 0  0  2  0  0  1  0  3  4  0]
 [ 0  0  9  0  0  0  0  0  1  0]
 [ 0  0  5  0  0  0  0  1  3  1]
 [ 0  0  3  0  0  0  0  3  1  3]
 [ 0  0  3  0  0  4  0  1  2  0]
 [ 0  0  3  0  0  1  0  1  5  0]
 [ 0  0  5  0  0  0  0  2  3  0]
 [ 0  0  1  0  0  0  0  3  6  0]
 [ 0  0  3  0  0  0  0  2  2  3]]
------------------------------------
Fitting Model With poly Kernel and Degree 16
Model Fitted


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.56
[[10  0  0  0  0  0  0  0  0  0]
 [ 0  0  6  0  0  0  0  2  2  0]
 [ 0  0 10  0  0  0  0  0  0  0]
 [ 0  0  5  0  0  0  0  0  5  0]
 [ 0  0  4  0  0  0  0  6  0  0]
 [ 0  0  1  0  0  8  0  1  0  0]
 [ 0  0  9  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0 10  0  0]
 [ 0  0  0  0  0  0  0  1  9  0]
 [ 0  0  0  0  0  0  0  1  0  9]]
------------------------------------
Fitting Model With poly Kernel and Degree 17
Model Fitted


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.43
[[10  0  0  0  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  0  0]
 [ 0  0  9  0  0  0  0  0  1  0]
 [ 0  6  3  0  0  0  0  0  1  0]
 [ 0  6  1  0  0  0  0  2  1  0]
 [ 0  3  3  0  0  4  0  0  0  0]
 [ 0  2  3  0  0  1  0  1  3  0]
 [ 0  6  1  0  0  0  0  1  2  0]
 [ 0  3  1  0  0  0  0  1  5  0]
 [ 0  0  2  0  0  0  0  2  2  4]]
------------------------------------
Fitting Model With poly Kernel and Degree 18
Model Fitted


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.57
[[10  0  0  0  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  0  0]
 [ 0  2  8  0  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  1  0  0]
 [ 0  4  1  0  0  4  0  1  0  0]
 [ 0  4  5  0  0  0  0  0  1  0]
 [ 0  2  0  0  0  0  0  8  0  0]
 [ 0  2  0  0  0  0  0  0  8  0]
 [ 0  0  0  0  0  0  0  1  0  9]]
------------------------------------
Fitting Model With poly Kernel and Degree 19
Model Fitted


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.43
[[10  0  0  0  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  0  0]
 [ 0  0  9  0  0  0  0  0  1  0]
 [ 0  6  3  0  0  0  0  0  1  0]
 [ 0  6  1  0  0  0  0  2  1  0]
 [ 0  3  3  0  0  4  0  0  0  0]
 [ 0  2  3  0  0  1  0  1  3  0]
 [ 0  6  1  0  0  0  0  1  2  0]
 [ 0  3  1  0  0  0  0  1  5  0]
 [ 0  0  2  0  0  0  0  2  2  4]]
------------------------------------
